### PR TITLE
Update music-service-async-interface

### PR DESCRIPTION
**Pull request by JuniorJPDJ**

### CODE REVIEW

**Comment by JuniorJPDJ** [comment]
Nvm

**Comment by wvffle** [comment]
Can't we specify it by the version?

**Comment by JuniorJPDJ** [comment]
@wvffle No, we will do versions when it will be at least partially stabilized :v

**Comment by wvffle** [comment]
are python modules following semver? Then we can do `1.0.0-alpha3`

**Comment by wvffle** [comment]
And of course not publish the package

**Comment by JuniorJPDJ** [comment]
@wvffle they does, but imo for this level of alpha 0.X.X is much better

**Comment by wvffle** [comment]
s/does/do/

Then I opt to use `0.0.1-alpha1`

**Comment by JuniorJPDJ** [comment]
The worst part about versioning it in this state is that we will need to grow version in both projects 23589423598 times a week.
For this moment I'd totally stay with commit hash.

**Comment by wvffle** [comment]
That's where semver resolves this problem. If poetry is implementing it correctly then we can add `^0.0.1-alpha` to dependencies and when we'll bump the alpha number, it should install the newest one

**Comment by wvffle** [comment]
I mean, we bump version in generic repo and then when we run `poetry install` in this repo, it should always use newest alpha

**Comment by JuniorJPDJ** [comment]
@wvffle So we could just dump specifing commit version and it would be the same atm and we already had conversation about specifing dep version so it keep working

**Comment by JuniorJPDJ** [comment]
@JuniorJPDJ eg. today changes would totally break old versions if commit hash wasnt specified

**Comment by JuniorJPDJ** [comment]
@JuniorJPDJ semver is cool if api already stabilized at least a bit but it still didnt

**Comment by wvffle** [comment]
> @JuniorJPDJ eg. today changes would totally break old versions if commit hash wasnt specified

That's why we're still in alpha. Don't expect that software in alpha stage will be backwards compatible

**Comment by JuniorJPDJ** [comment]
@wvffle And we already use semver, look at version definition in pyproject file

**Comment by wvffle** [comment]
> A pre-release version indicates that the version is unstable and **might not satisfy the intended compatibility requirements** as denoted by its associated normal version.

Taken from semver.org

**Pull request closed without merging**
